Neurolib:
  learning_rate: 0.001
  train_epochs: 10

Solar:
  learning_rate: 0.001
  train_epochs: 10

Atec:
  learning_rate: 0.001
  train_epochs: 10

Meter:
  learning_rate: 0.001
  train_epochs: 10

Temp:
  learning_rate: 0.001
  train_epochs: 10

Wind:
  learning_rate: 0.001
  train_epochs: 10

Traffic-CA:
  learning_rate: 0.001
  train_epochs: 10

Traffic-GLA:
  learning_rate: 0.001
  train_epochs: 10

Traffic-GBA:
  learning_rate: 0.001
  train_epochs: 10

Air Quality:
  learning_rate: 0.001
  train_epochs: 10

SIRS:
  learning_rate: 0.001
  train_epochs: 10

SP500:
  learning_rate: 0.001
  train_epochs: 10

M5:
  learning_rate: 0.001
  train_epochs: 10

Measles:
  learning_rate: 0.001
  train_epochs: 10

Wiki:
  learning_rate: 0.001
  train_epochs: 10

Mobility:
  learning_rate: 0.001
  train_epochs: 10

Rebound:
  learning_rate: 0.001
  train_epochs: 10

Wiki-2k:
  learning_rate: 0.001
  train_epochs: 10

Wiki-20k:
  learning_rate: 0.001
  train_epochs: 10

CalGeo-AirQuality-pm25:
  enc_in: 84
  seq_len: 14
  pred_len: 14
  freq: 'D'
  d_model: 128
  d_ff: 512
  e_layers: 2
  batch_size: 32
  learning_rate: 0.0001
  train_epochs: 50

CalGeo-AirQuality-ozone:
  enc_in: 156
  seq_len: 14
  pred_len: 14
  freq: 'D'
  d_model: 128
  d_ff: 512
  e_layers: 2
  batch_size: 32
  learning_rate: 0.0001
  train_epochs: 50

CalGeo-Solar-ghi:
  enc_in: 150
  seq_len: 14
  pred_len: 14
  freq: 'D'
  d_model: 128
  d_ff: 512
  e_layers: 2
  batch_size: 32
  learning_rate: 0.0001
  train_epochs: 50

CalGeo-Weather-tmax:
  enc_in: 560
  seq_len: 14
  pred_len: 14
  freq: 'D'
  d_model: 128
  d_ff: 512
  e_layers: 2
  batch_size: 32
  learning_rate: 0.0001
  train_epochs: 50

CalGeo-Weather-tmin:
  enc_in: 560
  seq_len: 14
  pred_len: 14
  freq: 'D'
  d_model: 128
  d_ff: 512
  e_layers: 2
  batch_size: 32
  learning_rate: 0.0001
  train_epochs: 50

CalGeo-Weather-prcp:
  enc_in: 703
  seq_len: 14
  pred_len: 14
  freq: 'D'
  d_model: 128
  d_ff: 512
  e_layers: 2
  batch_size: 16
  learning_rate: 0.0001
  train_epochs: 50

Mobility-CA-outdoor:
  enc_in: 970
  seq_len: 16
  pred_len: 4
  freq: 'W'
  d_model: 256
  d_ff: 1024
  e_layers: 2
  batch_size: 32
  learning_rate: 0.0001
  train_epochs: 50

Mobility-CA-essential:
  enc_in: 6286
  seq_len: 16
  pred_len: 4
  freq: 'W'
  d_model: 128
  d_ff: 512
  e_layers: 2
  batch_size: 8
  learning_rate: 0.0001
  train_epochs: 50

Mobility-CA-indoor:
  enc_in: 6427
  seq_len: 16
  pred_len: 4
  freq: 'W'
  d_model: 128
  d_ff: 512
  e_layers: 2
  batch_size: 8
  learning_rate: 0.0001
  train_epochs: 50

Mobility-CA-food:
  enc_in: 8474
  seq_len: 16
  pred_len: 4
  freq: 'W'
  d_model: 128
  d_ff: 512
  e_layers: 2
  batch_size: 4
  learning_rate: 0.0001
  train_epochs: 50
